//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pawprint.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_adopciones
    {
        
        public int IdAdopcion { get; set; }
        [Display(Name ="Fecha de adopción:")]
        [DataType(DataType.Date)]
        public string Fecha { get; set; }
        [Display(Name = "Disponibilidad:")]
        [Required(ErrorMessage ="Este campo es requerido")]
        public string Estado { get; set; }

        [Display(Name = "Animal:")]
        public Nullable<int> Animal { get; set; }
        [Display(Name = "Usuario quién lo adopta:")]
        public Nullable<int> Usuario { get; set; }
    
        public virtual tbl_animales tbl_animales { get; set; }
        public virtual tbl_usuarios tbl_usuarios { get; set; }
    }
}
