//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pawprint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_login()
        {
            this.tbl_usuarios = new HashSet<tbl_usuarios>();
        }
    
        public int IdLogin { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public Nullable<int> Rol { get; set; }
    
        public virtual tbl_roles tbl_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_usuarios> tbl_usuarios { get; set; }
    }
}
