//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pawprint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_animales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_animales()
        {
            this.tbl_adopciones = new HashSet<tbl_adopciones>();
        }
    
        public int IdAnimal { get; set; }
        public string Nombre { get; set; }
        public string Clase { get; set; }
        public string Sexo { get; set; }
        public int Edad { get; set; }
        public string Raza { get; set; }
        public string Tamaño { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string Peso { get; set; }
        public string Situacion { get; set; }
        public string Color { get; set; }
        public string Vacunas { get; set; }
        public string Temperamento { get; set; }
        public Nullable<int> Especie { get; set; }
        public Nullable<int> Poblacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_adopciones> tbl_adopciones { get; set; }
        public virtual tbl_especies tbl_especies { get; set; }
        public virtual tbl_poblacion tbl_poblacion { get; set; }
    }
}
