//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pawprint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reportes
    {
        public int IdReporte { get; set; }
        public string TipoAnimal { get; set; }
        public Nullable<int> TipoReporte { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
    
        public virtual tbl_tipoRep tbl_tipoRep { get; set; }
    }
}
